### PR TITLE
Setup Updates: SetupShop and GH Action

### PR DESCRIPTION
**Pull request by ric-evans**

### CODE REVIEW

**Comment by ric-evans** [comment]
@dsschult is that Docker Action supposed to be running in a PR?

**Comment by ric-evans** [comment]
there's a bunch of dependency conflicts with rest-tools, which is a "good" thing. Planning to bump a lot of reqs in `requirements.txt`

**Comment by dsschult** [comment]
> @dsschult is that Docker Action supposed to be running in a PR?

You mean the docker one?  Yes.  In a PR it just builds, but doesn't push.

**Comment by ric-evans** [comment]
> > @dsschult is that Docker Action supposed to be running in a PR?
> 
> You mean the docker one? Yes. In a PR it just builds, but doesn't push.

Got it. The issue looks to be the same as the other tests

**Pull request merged**
